### ISSUE TITLE
Variable name self.keys same for secrets and keyboard keys

### ISSUE THREAD

**Issue by japanish** [Heerkog/MicroPythonBLEHID#7]
Keyboard example errors
`Traceback (most recent call last):
  File "hid_services.py", line 622, in ble_irq
  File "hid_services.py", line 233, in ble_irq
AttributeError: 'list' object has no attribute 'items'`

changing self.keys variable name in keyboard class fixes

**Comment by Heerkog** [comment]
Thank you very much!
